language: go

os:
  - linux
  - osx

matrix:
  include:
  - go: "1.10"
    script:  go test -v ./...
  - go: "1.11"
    script: go test -v -mod=vendor ./...
  - go: "master"
    script: go test -v -mod=vendor ./...

env:
  - GO111MODULE=on