language: go

go:
  - "1.10"
  - "1.11"
  - "master"

os:
  - linux
  - osx

matrix:
  include:
  - go: "1.11"
    env:
      - GO111MODULE=on
  - go: "master"
    env:
      - GO111MODULE=on

script:
  - go get -d ./...
  - go test -v ./...